config/routes.rb
Rails.application.routes.draw do

  get 'uploads/new'

  get 'uploads/create'

  get 'uploads/index'

  authenticated :user do
    root to: 'projects#index', as: 'authenticated_root'
  end

  root 'home#index'
  ################
  # DEVISE
  ################
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations",
      passwords: "users/passwords"
  }
  resources :users do
    get 'users/dashboard', to: 'users#dashboard', as: 'dashboard'
    get 'users/profile', to: 'users#profile', as: 'profile'
    get 'edit_password', to: 'users#edit_password', as: 'edit_password'
  end

  ################
  # PROJECTS
  ################
  resources :projects do
    patch 'bookmark'
    resources :research_applications do
    end
  end

  resources :uploads

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id              :integer          not null, primary key
#  title           :string
#  subtitle        :string
#  startdate       :date
#  enddate         :date
#  app_deadline    :date
#  description     :text
#  hours_per_week  :integer
#  compensation    :integer
#  education_level :integer
#  state           :integer          default(1)
#  positions       :text             is an Array
#  questions       :text             is an Array
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  department      :text             is an Array
#  courses         :text             is an Array
#

class Project < ActiveRecord::Base
  attr_accessor
  enum state: [:active, :inactive]
  enum education_level: [:undergraduate, :graduate, :both]
  enum compensation: [:units, :paid, :other]
  enum department: [:engineeringcs, :economics]

  has_many :project_tags
  has_many :tags, through: :project_tags
  has_many :research_applications
  has_many :users, through: :research_applications

# Current_project is project object, tags is array of tag objects
  def add_tags(current_project, tags)
    tags.each do |tag|
      ProjectTag.create(tag: tag, project: current_project)
    end
  end

  def add_leader(current_project, user)
    ResearchApplication.create(project: current_project, user: user, status: 'leader')
  end
end

app/controllers/project_controller.rb
## Redundant: see projects_controller

class ProjectController < ApplicationController
  def index
    owner = User.find(params[:user_id])
    @owned_projects = owner.projects
  end

  def show
    project = Project.find(params[:id])
    @applications = project.applications
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @status = ResearchApplication.where(project_id: @project.id, user_id: current_user.id)
    @submittedapp = current_user.research_applications.where(project: @project, status: 2)
    @bookmarkedapp = current_user.research_applications.where(project: @project, status: 1)
  end

  def new
    @project = Project.new
    @tags = Tag.all
    @compensations = Project.compensations.keys
    @departments = Project.departments.keys
  end

  def create
    @project = Project.new(project_params)
    @project.positions = params[:positions]
    @project.questions = params[:questions]
    if @project.save
      @project.add_leader(@project, current_user)
      # @project.add_tags(@project, params[:skills])
      # @project.add_tags(@project, params[:courses])
      redirect_to @project
    else
      redirect_to action: 'new'
    end
  end

  def bookmark
    @project = Project.find(params[:project_id])
    ResearchApplication.create(project: @project, user: current_user, status: 1)
    redirect_to @project
  end

  def project_params
    params.require(:project).permit(:title, :subtitle, :startdate, :enddate, :app_deadline,
                                    :description, :hours_per_week, :compensation, :education_level, :field)
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_listings.html.erb
<div class="small-12 large-7 large-offset-2 columns">
	<% @projects.each do |project| %>
		<% @positions = project.positions %>
		<%= link_to project do %>
			<div class="large-12 columns listing">
				<div id="rectangle"></div>
				<div class="row left">
					<span class="large-12 columns title"><%= project.title %></span>
				</div>
				<div class="row fullWidth left">
					<span class="large-9 columns subtitle"><%= project.subtitle %></span>
					<span class="large-3 columns show-for-medium-up workload-top"><i class="fa fa-clock-o"></i> <%= project.hours_per_week %> hrs/wk </span>
				</div>
				<div class="row fullWidth left">
					<hr>
				</div>
				<div class="row fullWidth left">
					<div class="small-5 medium-7 large-8 columns hide-for-small-only bottom-infobar">
						<span class="looking-for">Looking For</span>
						<span class="positions">
							<% @positions.each do |position| %>
								<span class="position-pads"> <%= position %> </span>
							<% end %>
						</span>
					</div>
					<span class="small-5 columns show-for-small-only bottom-infobar workload-bot"><i class="fa fa-clock-o"></i> <%= project.hours_per_week %> hrs/wk </span>
					<span class="small-7 medium-5 large-4 date-pads">Posted: <%= project.updated_at.to_time.strftime("%b %d, %Y") %></span>

				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/projects/index.html.erb
projects index </br>
<% @projects.each do |p| %>
  <%= p.title %> <%= link_to p.title, project_path(p) %> </br>
<% end %>


<%= link_to 'new project', new_project_path%>
<% if user_signed_in? %>
  <%= link_to 'dashboard', user_dashboard_path(current_user)%>
  <%= link_to 'logout', destroy_user_session_path, method: :delete %>
<%end%>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
Title
<%= f.text_field :title,  placeholder: 'title' %>
Subtitle
<%= f.text_field :subtitle,  placeholder: 'subtitle' %>
Description
<%= f.text_field :description,  placeholder: 'description' %>
Basic info
What department does your project fall under?
<%= f.select(:department, @departments) %>
What kind of person are you looking for? Maximum 5



  <input type="text" name="positions[]" />
  <input type="text" name="positions[]" />
  <input type="text" name="positions[]" />
  <input type="text" name="positions[]" />
  <input type="text" name="positions[]" />


Form of compensation?
<%= f.select(:compensation, @compensations)%>
Hours per week?
<%= f.number_field :hours_per_week, class: :text_field, step: 0.5 %>
Project start date
<%= f.date_field :startdate %>
Project end date
<%= f.date_field :enddate%>
Application end date
<%= f.date_field :app_deadline%>
Add questions

<%= react_component "AddRemoveProjectQuestions", {project: @project } %>

<%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<%= @project %> </br>
title:
<%= @project.title %> </br>
subtitle:
<%= @project.subtitle %> </br>
description:
<%= @project.description %> </br>
startdate:
<%= @project.startdate %> </br>
enddate:
<%= @project.enddate %></br>
application deadline:
<%= @project.app_deadline %></br>
compensation:
<%= @project.compensation %></br>
Position
<% @project.positions.each do |position| %>
  <%= position %>
<% end %></br>
<%= link_to 'projects index', projects_path %>


<% if @submittedapp.empty? %>
<%= link_to 'apply', new_project_research_application_path(@project) %>
you've bookmarked this
<% elsif @bookmarkedapp.empty? && @submittedapp.empty? %>
<%= link_to 'bookmark', project_bookmark_path(@project), method: :patch %>
<% else %>

<%= link_to 'view application', project_research_application_path(@project, @submittedapp.first)%>
<%end%>