config/routes.rb
Rails.application.routes.draw do

  get 'uploads/new'

  get 'uploads/create'

  get 'uploads/index'

  authenticated :user do
    root to: 'projects#index', as: 'authenticated_root'
  end

  root 'home#index'
  ################
  # DEVISE
  ################
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations",
      passwords: "users/passwords"
  }
  resources :users do
    get 'users/dashboard', to: 'users#dashboard', as: 'dashboard'
    get 'users/profile', to: 'users#profile', as: 'profile'
    get 'edit_password', to: 'users#edit_password', as: 'edit_password'
  end

  ################
  # PROJECTS
  ################
  resources :projects do
    patch 'bookmark'
    resources :research_applications do
    end
  end

  resources :uploads

end

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
 
    <!-- Left Nav Section -->
    <%= link_to image_tag('ds_logo_resized3.png'), root_path %>
    <%= link_to 'Home', root_path%>
    <%= link_to 'Create', new_project_path%>

    <div class="right verticalLine">
      <% user_email = current_user.email %>
      <% email_index = user_email.index("@") %>
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <%= current_user.email[0,email_index] %>
          <ul class="menu">
            <div class="row">
                <%= link_to "Profile", root_path %>
            </div>
            <div class="row">
                <%= link_to "Dashboard", root_path %>
            </div>
            <div class="row">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            </div>
          </ul>
        </li>
      </ul>
    </div>

    <div class="show-for-medium-up right">
      <a href="#">About</a>
      <a href="#">Contact</a>
    </div>
  
</nav>
    

app/views/layouts/_nav_login.html.erb
<nav class="top-bar" data-topbar role="navigation">

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <%= link_to image_tag('ds_logo_resized3.png'), root_path %>
    <%= link_to 'Home', root_path%>

    <div class="right verticalLine">
      <%= link_to 'Log In', new_user_session_path, class: 'login_link' %>
      <%= link_to 'Register', new_user_registration_path, class: 'register_link' %>
    </div>

    <div class="show-for-medium-up right">
      <a href="#">About</a>
      <a href="#">Contact</a>
    </div>
  </section>
</nav>

app/views/layouts/_navbar.html.erb
<div class="contain-to-grid sticky">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Home', projects_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
          <li><%= link_to 'Dashboard', user_dashboard_path(current_user)%></li>
          <% end %>
          <li><a href="#">Listings</a></li>
          <li><%= link_to 'Create', new_project_path(current_user)%></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.firstname %> <%= current_user.lastname %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Dashboard', user_dashboard_path(current_user)%></li>
                <li><%= link_to 'Profile', user_profile_path(current_user)%></li>
                <li><%= link_to 'Edit Account', edit_user_registration_path%></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataHive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>